import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer/Footer";
import { Navbar } from "@/components/navbar/Navbar";
import { PreFooterCTA } from "@/components/footer/PreFooterCTA";
import { BackgroundSystem } from "@/components/layout/BackgroundSystem";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Živić-elektro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="hr_HR"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full">
        <BackgroundSystem />
        <div className="app-shell flex min-h-full flex-col">
          <Navbar />
          <main className="page-flow flex-1">{children}</main>
          <PreFooterCTA />
          <Footer />
        </div>
      </body>
    </html>
  );
}
